# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mehran Mehri
email: contact@mehranmehri.com
description: >- # this means to ignore newlines until "baseurl:"
  My Personal Website
baseurl: "my-website"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mnmehri
github_username:  mnmehri

# Build settings
markdown: kramdown

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'


sass:
  style: :expanded # You might prefer to minify using :compressed


theme: minima
plugins:
  - jekyll-feed
  # - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# default values for frontmatter yml. it applies automatically to any post in _posts directory
defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      #values
      layout: "post"
      author: "Mehran Mehri"
      permalink: /blogs/:categories/:title

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

highlighter: rouge
